# ICAMS_set_cat_globals.R

SetCatGlobals <- function() {
  # Set the values of globals needed to standardize the representation
  # catalogs in memory and on disk
  #
  # Results:
  #   Sets numerous globals; please see the code.
  #   
  #   IMPORTANT: this code depends on revc() which is defined in
  #   ICAMS_dependencies.R

  make.row.order1536 <- function() {
    # Make the row order of 1536 pentanucleotide mutation types.
    
    all4 <- c("A", "C", "G", "T")
    
    retval1 <- character(1536)
    retval2 <- character(1536)
    i <- 1
    
    for (center in c("C", 'T')) {
      for (alt in setdiff(all4, center)) {
        for (minus2 in all4) {
          for (minus1 in all4) {
            for (plus1 in all4) {
              for (plus2 in all4) {
                retval1[i] <- 
                  paste0(minus2, minus1, center, plus1, plus2, alt)
                retval2[i] <-
                  paste0(center, alt, minus2, minus1, plus1, plus2)
                i <- i + 1
              }
            }
          }
        }     
      }
    }
    return(list(standard = retval1, mini = retval2))
  }
  
  .catalog.row.order1536 <<- make.row.order1536()$standard
  
  .catalog.row.order192 <<- 
    c("AAAC","AACC","AAGC","AATC","CAAC","CACC","CAGC","CATC","GAAC",
      "GACC","GAGC","GATC","TAAC","TACC","TAGC","TATC","AAAG","AACG",
      "AAGG","AATG","CAAG","CACG","CAGG","CATG","GAAG","GACG","GAGG",
      "GATG","TAAG","TACG","TAGG","TATG","AAAT","AACT","AAGT","AATT",
      "CAAT","CACT","CAGT","CATT","GAAT","GACT","GAGT","GATT","TAAT",
      "TACT","TAGT","TATT","ACAA","ACCA","ACGA","ACTA","CCAA","CCCA",
      "CCGA","CCTA","GCAA","GCCA","GCGA","GCTA","TCAA","TCCA","TCGA",
      "TCTA","ACAG","ACCG","ACGG","ACTG","CCAG","CCCG","CCGG","CCTG",
      "GCAG","GCCG","GCGG","GCTG","TCAG","TCCG","TCGG","TCTG","ACAT",
      "ACCT","ACGT","ACTT","CCAT","CCCT","CCGT","CCTT","GCAT","GCCT",
      "GCGT","GCTT","TCAT","TCCT","TCGT","TCTT","AGAA","AGCA","AGGA",
      "AGTA","CGAA","CGCA","CGGA","CGTA","GGAA","GGCA","GGGA","GGTA",
      "TGAA","TGCA","TGGA","TGTA","AGAC","AGCC","AGGC","AGTC","CGAC",
      "CGCC","CGGC","CGTC","GGAC","GGCC","GGGC","GGTC","TGAC","TGCC",
      "TGGC","TGTC","AGAT","AGCT","AGGT","AGTT","CGAT","CGCT","CGGT",
      "CGTT","GGAT","GGCT","GGGT","GGTT","TGAT","TGCT","TGGT","TGTT",
      "ATAA","ATCA","ATGA","ATTA","CTAA","CTCA","CTGA","CTTA","GTAA",
      "GTCA","GTGA","GTTA","TTAA","TTCA","TTGA","TTTA","ATAC","ATCC",
      "ATGC","ATTC","CTAC","CTCC","CTGC","CTTC","GTAC","GTCC","GTGC",
      "GTTC","TTAC","TTCC","TTGC","TTTC","ATAG","ATCG","ATGG","ATTG",
      "CTAG","CTCG","CTGG","CTTG","GTAG","GTCG","GTGG","GTTG","TTAG",
      "TTCG","TTGG","TTTG")
  
  .catalog.row.order96 <<-
    c("ACAA", "ACCA", "ACGA", "ACTA", "CCAA", "CCCA", "CCGA", "CCTA",
      "GCAA", "GCCA", "GCGA", "GCTA", "TCAA", "TCCA", "TCGA", "TCTA",
      "ACAG", "ACCG", "ACGG", "ACTG", "CCAG", "CCCG", "CCGG", "CCTG",
      "GCAG", "GCCG", "GCGG", "GCTG", "TCAG", "TCCG", "TCGG", "TCTG",
      "ACAT", "ACCT", "ACGT", "ACTT", "CCAT", "CCCT", "CCGT", "CCTT",
      "GCAT", "GCCT", "GCGT", "GCTT", "TCAT", "TCCT", "TCGT", "TCTT",
      "ATAA", "ATCA", "ATGA", "ATTA", "CTAA", "CTCA", "CTGA", "CTTA",
      "GTAA", "GTCA", "GTGA", "GTTA", "TTAA", "TTCA", "TTGA", "TTTA",
      "ATAC", "ATCC", "ATGC", "ATTC", "CTAC", "CTCC", "CTGC", "CTTC",
      "GTAC", "GTCC", "GTGC", "GTTC", "TTAC", "TTCC", "TTGC", "TTTC",
      "ATAG", "ATCG", "ATGG", "ATTG", "CTAG", "CTCG", "CTGG", "CTTG",
      "GTAG", "GTCG", "GTGG", "GTTG", "TTAG", "TTCG", "TTGG", "TTTG"
    )
  
  # The first two letters are reference bases while the 
  # last two letters are the altered bases after mutation.
  .catalog.row.order.DNS <<- 
    c("ACCA", "ACCG", "ACCT", "ACGA", "ACGG", "ACGT", "ACTA", "ACTG", 
      "ACTT", "ATCA", "ATCC", "ATCG", "ATGA", "ATGC", "ATTA", "CCAA", 
      "CCAG", "CCAT", "CCGA", "CCGG", "CCGT", "CCTA", "CCTG", "CCTT", 
      "CGAT", "CGGC", "CGGT", "CGTA", "CGTC", "CGTT", "CTAA", "CTAC", 
      "CTAG", "CTGA", "CTGC", "CTGG", "CTTA", "CTTC", "CTTG", "GCAA", 
      "GCAG", "GCAT", "GCCA", "GCCG", "GCTA", "TAAT", "TACG", "TACT", 
      "TAGC", "TAGG", "TAGT", "TCAA", "TCAG", "TCAT", "TCCA", "TCCG", 
      "TCCT", "TCGA", "TCGG", "TCGT", "TGAA", "TGAC", "TGAT", "TGCA", 
      "TGCC", "TGCT", "TGGA", "TGGC", "TGGT", "TTAA", "TTAC", "TTAG", 
      "TTCA", "TTCC", "TTCG", "TTGA", "TTGC", "TTGG")
  
  # There are 144 stranded DNSs: 4 X 4 sources and 3 X 3 alternates;
  # 4 x 4 x 3 x 3 = 144.
  .catalog.row.order.DNS.144 <<- 
    c("AACC", "AACG", "AACT", "AAGC", "AAGG", "AAGT", "AATC", "AATG", 
      "AATT", "ACCA", "ACCG", "ACCT", "ACGA", "ACGG", "ACGT", "ACTA", 
      "ACTG", "ACTT", "AGCA", "AGCC", "AGCT", "AGGA", "AGGC", "AGGT", 
      "AGTA", "AGTC", "AGTT", "ATCA", "ATCC", "ATCG", "ATGA", "ATGC", 
      "ATGG", "ATTA", "ATTC", "ATTG", "CAAC", "CAAG", "CAAT", "CAGC", 
      "CAGG", "CAGT", "CATC", "CATG", "CATT", "CCAA", "CCAG", "CCAT", 
      "CCGA", "CCGG", "CCGT", "CCTA", "CCTG", "CCTT", "CGAA", "CGAC", 
      "CGAT", "CGGA", "CGGC", "CGGT", "CGTA", "CGTC", "CGTT", "CTAA", 
      "CTAC", "CTAG", "CTGA", "CTGC", "CTGG", "CTTA", "CTTC", "CTTG", 
      "GAAC", "GAAG", "GAAT", "GACC", "GACG", "GACT", "GATC", "GATG", 
      "GATT", "GCAA", "GCAG", "GCAT", "GCCA", "GCCG", "GCCT", "GCTA", 
      "GCTG", "GCTT", "GGAA", "GGAC", "GGAT", "GGCA", "GGCC", "GGCT", 
      "GGTA", "GGTC", "GGTT", "GTAA", "GTAC", "GTAG", "GTCA", "GTCC", 
      "GTCG", "GTTA", "GTTC", "GTTG", "TAAC", "TAAG", "TAAT", "TACC", 
      "TACG", "TACT", "TAGC", "TAGG", "TAGT", "TCAA", "TCAG", "TCAT", 
      "TCCA", "TCCG", "TCCT", "TCGA", "TCGG", "TCGT", "TGAA", "TGAC", 
      "TGAT", "TGCA", "TGCC", "TGCT", "TGGA", "TGGC", "TGGT", "TTAA", 
      "TTAC", "TTAG", "TTCA", "TTCC", "TTCG", "TTGA", "TTGC", "TTGG"
    )
  
  .catalog.row.order.ID <<-
    c("DEL:C:1:0", "DEL:C:1:1", "DEL:C:1:2", "DEL:C:1:3", "DEL:C:1:4", 
      "DEL:C:1:5+", "DEL:T:1:0", "DEL:T:1:1", "DEL:T:1:2", "DEL:T:1:3", 
      "DEL:T:1:4", "DEL:T:1:5+", "INS:C:1:0", "INS:C:1:1", "INS:C:1:2", 
      "INS:C:1:3", "INS:C:1:4", "INS:C:1:5+", "INS:T:1:0", "INS:T:1:1", 
      "INS:T:1:2", "INS:T:1:3", "INS:T:1:4", "INS:T:1:5+", "DEL:repeats:2:0", 
      "DEL:repeats:2:1", "DEL:repeats:2:2", "DEL:repeats:2:3", "DEL:repeats:2:4", 
      "DEL:repeats:2:5+", "DEL:repeats:3:0", "DEL:repeats:3:1", "DEL:repeats:3:2", 
      "DEL:repeats:3:3", "DEL:repeats:3:4", "DEL:repeats:3:5+", "DEL:repeats:4:0", 
      "DEL:repeats:4:1", "DEL:repeats:4:2", "DEL:repeats:4:3", "DEL:repeats:4:4", 
      "DEL:repeats:4:5+", "DEL:repeats:5+:0", "DEL:repeats:5+:1", "DEL:repeats:5+:2", 
      "DEL:repeats:5+:3", "DEL:repeats:5+:4", "DEL:repeats:5+:5+", 
      "INS:repeats:2:0", "INS:repeats:2:1", "INS:repeats:2:2", "INS:repeats:2:3", 
      "INS:repeats:2:4", "INS:repeats:2:5+", "INS:repeats:3:0", "INS:repeats:3:1", 
      "INS:repeats:3:2", "INS:repeats:3:3", "INS:repeats:3:4", "INS:repeats:3:5+", 
      "INS:repeats:4:0", "INS:repeats:4:1", "INS:repeats:4:2", "INS:repeats:4:3", 
      "INS:repeats:4:4", "INS:repeats:4:5+", "INS:repeats:5+:0", "INS:repeats:5+:1", 
      "INS:repeats:5+:2", "INS:repeats:5+:3", "INS:repeats:5+:4", "INS:repeats:5+:5+", 
      "DEL:MH:2:1", "DEL:MH:3:1", "DEL:MH:3:2", "DEL:MH:4:1", "DEL:MH:4:2", 
      "DEL:MH:4:3", "DEL:MH:5+:1", "DEL:MH:5+:2", "DEL:MH:5+:3", "DEL:MH:5+:4", 
      "DEL:MH:5+:5+")
  
  ##############################################################
  # Next are "empty row headers", data frames with the columns
  # need to write catalogs to disk.
  ##############################################################
  
  .ct.96.row.headers <<- 
    structure(
      list(
        `Mutation type` =
          c("C>A", "C>A", "C>A", "C>A", 
            "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", 
            "C>A", "C>A", "C>A", "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", 
            "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", 
            "C>G", "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", 
            "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", "T>A", 
            "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", 
            "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", "T>C", "T>C", "T>C", 
            "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", 
            "T>C", "T>C", "T>C", "T>C", "T>G", "T>G", "T>G", "T>G", "T>G", 
            "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", 
            "T>G", "T>G"), 
        Trinucleotide = 
          c("ACA", "ACC", "ACG", "ACT", 
            "CCA", "CCC", "CCG", "CCT", "GCA", "GCC", "GCG", "GCT", "TCA", 
            "TCC", "TCG", "TCT", "ACA", "ACC", "ACG", "ACT", "CCA", "CCC", 
            "CCG", "CCT", "GCA", "GCC", "GCG", "GCT", "TCA", "TCC", "TCG", 
            "TCT", "ACA", "ACC", "ACG", "ACT", "CCA", "CCC", "CCG", "CCT", 
            "GCA", "GCC", "GCG", "GCT", "TCA", "TCC", "TCG", "TCT", "ATA", 
            "ATC", "ATG", "ATT", "CTA", "CTC", "CTG", "CTT", "GTA", "GTC", 
            "GTG", "GTT", "TTA", "TTC", "TTG", "TTT", "ATA", "ATC", "ATG", 
            "ATT", "CTA", "CTC", "CTG", "CTT", "GTA", "GTC", "GTG", "GTT", 
            "TTA", "TTC", "TTG", "TTT", "ATA", "ATC", "ATG", "ATT", "CTA", 
            "CTC", "CTG", "CTT", "GTA", "GTC", "GTG", "GTT", "TTA", "TTC", 
            "TTG", "TTT")), 
      class = c("data.table", "data.frame"), 
      row.names = c(NA, -96L)
      # , .internal.selfref = <pointer: 0x0000000002551ef0> 
    )
  
  .ct.192.row.headers <<- 
    structure(
      list(
        Strand = 
          c("T", "T", "T", "T", "T", "T", "T", 
            "T", "T", "T", "T", "T", "T", "T", "T", "T", "T", "T", "T", "T", 
            "T", "T", "T", "T", "T", "T", "T", "T", "T", "T", "T", "T", "T", 
            "T", "T", "T", "T", "T", "T", "T", "T", "T", "T", "T", "T", "T", 
            "T", "T", "U", "U", "U", "U", "U", "U", "U", "U", "U", "U", "U", 
            "U", "U", "U", "U", "U", "U", "U", "U", "U", "U", "U", "U", "U", 
            "U", "U", "U", "U", "U", "U", "U", "U", "U", "U", "U", "U", "U", 
            "U", "U", "U", "U", "U", "U", "U", "U", "U", "U", "U", "T", "T", 
            "T", "T", "T", "T", "T", "T", "T", "T", "T", "T", "T", "T", "T", 
            "T", "T", "T", "T", "T", "T", "T", "T", "T", "T", "T", "T", "T", 
            "T", "T", "T", "T", "T", "T", "T", "T", "T", "T", "T", "T", "T", 
            "T", "T", "T", "T", "T", "T", "T", "U", "U", "U", "U", "U", "U", 
            "U", "U", "U", "U", "U", "U", "U", "U", "U", "U", "U", "U", "U", 
            "U", "U", "U", "U", "U", "U", "U", "U", "U", "U", "U", "U", "U", 
            "U", "U", "U", "U", "U", "U", "U", "U", "U", "U", "U", "U", "U", 
            "U", "U", "U"), 
        `Mutation type` =
          c("T>G", "T>G", "T>G", "T>G", 
            "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", 
            "T>G", "T>G", "T>G", "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", 
            "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", 
            "T>C", "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", 
            "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", "C>A", 
            "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", 
            "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", "C>G", "C>G", "C>G", 
            "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", 
            "C>G", "C>G", "C>G", "C>G", "C>T", "C>T", "C>T", "C>T", "C>T", 
            "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", 
            "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", 
            "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", 
            "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", 
            "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", "C>A", "C>A", 
            "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", 
            "C>A", "C>A", "C>A", "C>A", "C>A", "T>A", "T>A", "T>A", "T>A", 
            "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", 
            "T>A", "T>A", "T>A", "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", 
            "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", 
            "T>C", "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", 
            "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", "T>G"),
        Trinucleotide = 
          c("TTT", 
            "GTT", "CTT", "ATT", "TTG", "GTG", "CTG", "ATG", "TTC", "GTC", 
            "CTC", "ATC", "TTA", "GTA", "CTA", "ATA", "TTT", "GTT", "CTT", 
            "ATT", "TTG", "GTG", "CTG", "ATG", "TTC", "GTC", "CTC", "ATC", 
            "TTA", "GTA", "CTA", "ATA", "TTT", "GTT", "CTT", "ATT", "TTG", 
            "GTG", "CTG", "ATG", "TTC", "GTC", "CTC", "ATC", "TTA", "GTA", 
            "CTA", "ATA", "ACA", "ACC", "ACG", "ACT", "CCA", "CCC", "CCG", 
            "CCT", "GCA", "GCC", "GCG", "GCT", "TCA", "TCC", "TCG", "TCT", 
            "ACA", "ACC", "ACG", "ACT", "CCA", "CCC", "CCG", "CCT", "GCA", 
            "GCC", "GCG", "GCT", "TCA", "TCC", "TCG", "TCT", "ACA", "ACC", 
            "ACG", "ACT", "CCA", "CCC", "CCG", "CCT", "GCA", "GCC", "GCG", 
            "GCT", "TCA", "TCC", "TCG", "TCT", "TCT", "GCT", "CCT", "ACT", 
            "TCG", "GCG", "CCG", "ACG", "TCC", "GCC", "CCC", "ACC", "TCA", 
            "GCA", "CCA", "ACA", "TCT", "GCT", "CCT", "ACT", "TCG", "GCG", 
            "CCG", "ACG", "TCC", "GCC", "CCC", "ACC", "TCA", "GCA", "CCA", 
            "ACA", "TCT", "GCT", "CCT", "ACT", "TCG", "GCG", "CCG", "ACG", 
            "TCC", "GCC", "CCC", "ACC", "TCA", "GCA", "CCA", "ACA", "ATA", 
            "ATC", "ATG", "ATT", "CTA", "CTC", "CTG", "CTT", "GTA", "GTC", 
            "GTG", "GTT", "TTA", "TTC", "TTG", "TTT", "ATA", "ATC", "ATG", 
            "ATT", "CTA", "CTC", "CTG", "CTT", "GTA", "GTC", "GTG", "GTT", 
            "TTA", "TTC", "TTG", "TTT", "ATA", "ATC", "ATG", "ATT", "CTA", 
            "CTC", "CTG", "CTT", "GTA", "GTC", "GTG", "GTT", "TTA", "TTC", 
            "TTG", "TTT")),
      class = c("data.table", "data.frame"), 
      row.names = c(NA, -192L)
      # .internal.selfref = <pointer: 0x0000000002551ef0>
    )
  
  .ct.1536.row.headers <<-
    structure(
      list(
        `Mutation type` = 
          c("C>A", "C>A", "C>A", "C>A", 
            "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", 
            "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", 
            "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", 
            "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", 
            "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", 
            "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", 
            "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", 
            "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", 
            "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", 
            "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", 
            "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", 
            "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", 
            "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", 
            "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", 
            "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", 
            "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", 
            "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", 
            "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", 
            "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", 
            "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", 
            "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", 
            "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", 
            "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", 
            "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", 
            "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", 
            "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", 
            "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", 
            "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", "C>A", 
            "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", 
            "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", 
            "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", 
            "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", 
            "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", 
            "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", 
            "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", 
            "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", 
            "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", 
            "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", 
            "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", 
            "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", 
            "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", 
            "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", 
            "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", 
            "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", 
            "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", 
            "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", 
            "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", 
            "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", 
            "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", 
            "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", 
            "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", 
            "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", 
            "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", 
            "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", 
            "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", 
            "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", "C>G", 
            "C>G", "C>G", "C>G", "C>G", "C>T", "C>T", "C>T", "C>T", "C>T", 
            "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", 
            "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", 
            "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", 
            "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", 
            "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", 
            "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", 
            "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", 
            "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", 
            "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", 
            "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", 
            "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", 
            "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", 
            "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", 
            "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", 
            "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", 
            "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", 
            "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", 
            "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", 
            "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", 
            "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", 
            "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", 
            "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", 
            "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", 
            "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", 
            "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", 
            "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", 
            "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", 
            "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", "C>T", "T>A", 
            "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", 
            "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", 
            "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", 
            "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", 
            "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", 
            "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", 
            "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", 
            "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", 
            "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", 
            "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", 
            "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", 
            "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", 
            "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", 
            "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", 
            "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", 
            "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", 
            "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", 
            "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", 
            "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", 
            "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", 
            "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", 
            "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", 
            "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", 
            "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", 
            "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", 
            "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", 
            "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", 
            "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", "T>A", 
            "T>A", "T>A", "T>A", "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", 
            "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", 
            "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", 
            "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", 
            "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", 
            "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", 
            "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", 
            "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", 
            "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", 
            "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", 
            "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", 
            "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", 
            "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", 
            "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", 
            "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", 
            "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", 
            "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", 
            "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", 
            "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", 
            "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", 
            "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", 
            "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", 
            "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", 
            "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", 
            "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", 
            "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", 
            "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", 
            "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", 
            "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", "T>C", "T>G", "T>G", 
            "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", 
            "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", 
            "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", 
            "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", 
            "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", 
            "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", 
            "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", 
            "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", 
            "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", 
            "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", 
            "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", 
            "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", 
            "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", 
            "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", 
            "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", 
            "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", 
            "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", 
            "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", 
            "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", 
            "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", 
            "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", 
            "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", 
            "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", 
            "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", 
            "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", 
            "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", 
            "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", 
            "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", "T>G", 
            "T>G", "T>G"),
        Pentanucleotide = 
          c("AACAA", "AACAC", "AACAG", 
            "AACAT", "AACCA", "AACCC", "AACCG", "AACCT", "AACGA", "AACGC", 
            "AACGG", "AACGT", "AACTA", "AACTC", "AACTG", "AACTT", "ACCAA", 
            "ACCAC", "ACCAG", "ACCAT", "ACCCA", "ACCCC", "ACCCG", "ACCCT", 
            "ACCGA", "ACCGC", "ACCGG", "ACCGT", "ACCTA", "ACCTC", "ACCTG", 
            "ACCTT", "AGCAA", "AGCAC", "AGCAG", "AGCAT", "AGCCA", "AGCCC", 
            "AGCCG", "AGCCT", "AGCGA", "AGCGC", "AGCGG", "AGCGT", "AGCTA", 
            "AGCTC", "AGCTG", "AGCTT", "ATCAA", "ATCAC", "ATCAG", "ATCAT", 
            "ATCCA", "ATCCC", "ATCCG", "ATCCT", "ATCGA", "ATCGC", "ATCGG", 
            "ATCGT", "ATCTA", "ATCTC", "ATCTG", "ATCTT", "CACAA", "CACAC", 
            "CACAG", "CACAT", "CACCA", "CACCC", "CACCG", "CACCT", "CACGA", 
            "CACGC", "CACGG", "CACGT", "CACTA", "CACTC", "CACTG", "CACTT", 
            "CCCAA", "CCCAC", "CCCAG", "CCCAT", "CCCCA", "CCCCC", "CCCCG", 
            "CCCCT", "CCCGA", "CCCGC", "CCCGG", "CCCGT", "CCCTA", "CCCTC", 
            "CCCTG", "CCCTT", "CGCAA", "CGCAC", "CGCAG", "CGCAT", "CGCCA", 
            "CGCCC", "CGCCG", "CGCCT", "CGCGA", "CGCGC", "CGCGG", "CGCGT", 
            "CGCTA", "CGCTC", "CGCTG", "CGCTT", "CTCAA", "CTCAC", "CTCAG", 
            "CTCAT", "CTCCA", "CTCCC", "CTCCG", "CTCCT", "CTCGA", "CTCGC", 
            "CTCGG", "CTCGT", "CTCTA", "CTCTC", "CTCTG", "CTCTT", "GACAA", 
            "GACAC", "GACAG", "GACAT", "GACCA", "GACCC", "GACCG", "GACCT", 
            "GACGA", "GACGC", "GACGG", "GACGT", "GACTA", "GACTC", "GACTG", 
            "GACTT", "GCCAA", "GCCAC", "GCCAG", "GCCAT", "GCCCA", "GCCCC", 
            "GCCCG", "GCCCT", "GCCGA", "GCCGC", "GCCGG", "GCCGT", "GCCTA", 
            "GCCTC", "GCCTG", "GCCTT", "GGCAA", "GGCAC", "GGCAG", "GGCAT", 
            "GGCCA", "GGCCC", "GGCCG", "GGCCT", "GGCGA", "GGCGC", "GGCGG", 
            "GGCGT", "GGCTA", "GGCTC", "GGCTG", "GGCTT", "GTCAA", "GTCAC", 
            "GTCAG", "GTCAT", "GTCCA", "GTCCC", "GTCCG", "GTCCT", "GTCGA", 
            "GTCGC", "GTCGG", "GTCGT", "GTCTA", "GTCTC", "GTCTG", "GTCTT", 
            "TACAA", "TACAC", "TACAG", "TACAT", "TACCA", "TACCC", "TACCG", 
            "TACCT", "TACGA", "TACGC", "TACGG", "TACGT", "TACTA", "TACTC", 
            "TACTG", "TACTT", "TCCAA", "TCCAC", "TCCAG", "TCCAT", "TCCCA", 
            "TCCCC", "TCCCG", "TCCCT", "TCCGA", "TCCGC", "TCCGG", "TCCGT", 
            "TCCTA", "TCCTC", "TCCTG", "TCCTT", "TGCAA", "TGCAC", "TGCAG", 
            "TGCAT", "TGCCA", "TGCCC", "TGCCG", "TGCCT", "TGCGA", "TGCGC", 
            "TGCGG", "TGCGT", "TGCTA", "TGCTC", "TGCTG", "TGCTT", "TTCAA", 
            "TTCAC", "TTCAG", "TTCAT", "TTCCA", "TTCCC", "TTCCG", "TTCCT", 
            "TTCGA", "TTCGC", "TTCGG", "TTCGT", "TTCTA", "TTCTC", "TTCTG", 
            "TTCTT", "AACAA", "AACAC", "AACAG", "AACAT", "AACCA", "AACCC", 
            "AACCG", "AACCT", "AACGA", "AACGC", "AACGG", "AACGT", "AACTA", 
            "AACTC", "AACTG", "AACTT", "ACCAA", "ACCAC", "ACCAG", "ACCAT", 
            "ACCCA", "ACCCC", "ACCCG", "ACCCT", "ACCGA", "ACCGC", "ACCGG", 
            "ACCGT", "ACCTA", "ACCTC", "ACCTG", "ACCTT", "AGCAA", "AGCAC", 
            "AGCAG", "AGCAT", "AGCCA", "AGCCC", "AGCCG", "AGCCT", "AGCGA", 
            "AGCGC", "AGCGG", "AGCGT", "AGCTA", "AGCTC", "AGCTG", "AGCTT", 
            "ATCAA", "ATCAC", "ATCAG", "ATCAT", "ATCCA", "ATCCC", "ATCCG", 
            "ATCCT", "ATCGA", "ATCGC", "ATCGG", "ATCGT", "ATCTA", "ATCTC", 
            "ATCTG", "ATCTT", "CACAA", "CACAC", "CACAG", "CACAT", "CACCA", 
            "CACCC", "CACCG", "CACCT", "CACGA", "CACGC", "CACGG", "CACGT", 
            "CACTA", "CACTC", "CACTG", "CACTT", "CCCAA", "CCCAC", "CCCAG", 
            "CCCAT", "CCCCA", "CCCCC", "CCCCG", "CCCCT", "CCCGA", "CCCGC", 
            "CCCGG", "CCCGT", "CCCTA", "CCCTC", "CCCTG", "CCCTT", "CGCAA", 
            "CGCAC", "CGCAG", "CGCAT", "CGCCA", "CGCCC", "CGCCG", "CGCCT", 
            "CGCGA", "CGCGC", "CGCGG", "CGCGT", "CGCTA", "CGCTC", "CGCTG", 
            "CGCTT", "CTCAA", "CTCAC", "CTCAG", "CTCAT", "CTCCA", "CTCCC", 
            "CTCCG", "CTCCT", "CTCGA", "CTCGC", "CTCGG", "CTCGT", "CTCTA", 
            "CTCTC", "CTCTG", "CTCTT", "GACAA", "GACAC", "GACAG", "GACAT", 
            "GACCA", "GACCC", "GACCG", "GACCT", "GACGA", "GACGC", "GACGG", 
            "GACGT", "GACTA", "GACTC", "GACTG", "GACTT", "GCCAA", "GCCAC", 
            "GCCAG", "GCCAT", "GCCCA", "GCCCC", "GCCCG", "GCCCT", "GCCGA", 
            "GCCGC", "GCCGG", "GCCGT", "GCCTA", "GCCTC", "GCCTG", "GCCTT", 
            "GGCAA", "GGCAC", "GGCAG", "GGCAT", "GGCCA", "GGCCC", "GGCCG", 
            "GGCCT", "GGCGA", "GGCGC", "GGCGG", "GGCGT", "GGCTA", "GGCTC", 
            "GGCTG", "GGCTT", "GTCAA", "GTCAC", "GTCAG", "GTCAT", "GTCCA", 
            "GTCCC", "GTCCG", "GTCCT", "GTCGA", "GTCGC", "GTCGG", "GTCGT", 
            "GTCTA", "GTCTC", "GTCTG", "GTCTT", "TACAA", "TACAC", "TACAG", 
            "TACAT", "TACCA", "TACCC", "TACCG", "TACCT", "TACGA", "TACGC", 
            "TACGG", "TACGT", "TACTA", "TACTC", "TACTG", "TACTT", "TCCAA", 
            "TCCAC", "TCCAG", "TCCAT", "TCCCA", "TCCCC", "TCCCG", "TCCCT", 
            "TCCGA", "TCCGC", "TCCGG", "TCCGT", "TCCTA", "TCCTC", "TCCTG", 
            "TCCTT", "TGCAA", "TGCAC", "TGCAG", "TGCAT", "TGCCA", "TGCCC", 
            "TGCCG", "TGCCT", "TGCGA", "TGCGC", "TGCGG", "TGCGT", "TGCTA", 
            "TGCTC", "TGCTG", "TGCTT", "TTCAA", "TTCAC", "TTCAG", "TTCAT", 
            "TTCCA", "TTCCC", "TTCCG", "TTCCT", "TTCGA", "TTCGC", "TTCGG", 
            "TTCGT", "TTCTA", "TTCTC", "TTCTG", "TTCTT", "AACAA", "AACAC", 
            "AACAG", "AACAT", "AACCA", "AACCC", "AACCG", "AACCT", "AACGA", 
            "AACGC", "AACGG", "AACGT", "AACTA", "AACTC", "AACTG", "AACTT", 
            "ACCAA", "ACCAC", "ACCAG", "ACCAT", "ACCCA", "ACCCC", "ACCCG", 
            "ACCCT", "ACCGA", "ACCGC", "ACCGG", "ACCGT", "ACCTA", "ACCTC", 
            "ACCTG", "ACCTT", "AGCAA", "AGCAC", "AGCAG", "AGCAT", "AGCCA", 
            "AGCCC", "AGCCG", "AGCCT", "AGCGA", "AGCGC", "AGCGG", "AGCGT", 
            "AGCTA", "AGCTC", "AGCTG", "AGCTT", "ATCAA", "ATCAC", "ATCAG", 
            "ATCAT", "ATCCA", "ATCCC", "ATCCG", "ATCCT", "ATCGA", "ATCGC", 
            "ATCGG", "ATCGT", "ATCTA", "ATCTC", "ATCTG", "ATCTT", "CACAA", 
            "CACAC", "CACAG", "CACAT", "CACCA", "CACCC", "CACCG", "CACCT", 
            "CACGA", "CACGC", "CACGG", "CACGT", "CACTA", "CACTC", "CACTG", 
            "CACTT", "CCCAA", "CCCAC", "CCCAG", "CCCAT", "CCCCA", "CCCCC", 
            "CCCCG", "CCCCT", "CCCGA", "CCCGC", "CCCGG", "CCCGT", "CCCTA", 
            "CCCTC", "CCCTG", "CCCTT", "CGCAA", "CGCAC", "CGCAG", "CGCAT", 
            "CGCCA", "CGCCC", "CGCCG", "CGCCT", "CGCGA", "CGCGC", "CGCGG", 
            "CGCGT", "CGCTA", "CGCTC", "CGCTG", "CGCTT", "CTCAA", "CTCAC", 
            "CTCAG", "CTCAT", "CTCCA", "CTCCC", "CTCCG", "CTCCT", "CTCGA", 
            "CTCGC", "CTCGG", "CTCGT", "CTCTA", "CTCTC", "CTCTG", "CTCTT", 
            "GACAA", "GACAC", "GACAG", "GACAT", "GACCA", "GACCC", "GACCG", 
            "GACCT", "GACGA", "GACGC", "GACGG", "GACGT", "GACTA", "GACTC", 
            "GACTG", "GACTT", "GCCAA", "GCCAC", "GCCAG", "GCCAT", "GCCCA", 
            "GCCCC", "GCCCG", "GCCCT", "GCCGA", "GCCGC", "GCCGG", "GCCGT", 
            "GCCTA", "GCCTC", "GCCTG", "GCCTT", "GGCAA", "GGCAC", "GGCAG", 
            "GGCAT", "GGCCA", "GGCCC", "GGCCG", "GGCCT", "GGCGA", "GGCGC", 
            "GGCGG", "GGCGT", "GGCTA", "GGCTC", "GGCTG", "GGCTT", "GTCAA", 
            "GTCAC", "GTCAG", "GTCAT", "GTCCA", "GTCCC", "GTCCG", "GTCCT", 
            "GTCGA", "GTCGC", "GTCGG", "GTCGT", "GTCTA", "GTCTC", "GTCTG", 
            "GTCTT", "TACAA", "TACAC", "TACAG", "TACAT", "TACCA", "TACCC", 
            "TACCG", "TACCT", "TACGA", "TACGC", "TACGG", "TACGT", "TACTA", 
            "TACTC", "TACTG", "TACTT", "TCCAA", "TCCAC", "TCCAG", "TCCAT", 
            "TCCCA", "TCCCC", "TCCCG", "TCCCT", "TCCGA", "TCCGC", "TCCGG", 
            "TCCGT", "TCCTA", "TCCTC", "TCCTG", "TCCTT", "TGCAA", "TGCAC", 
            "TGCAG", "TGCAT", "TGCCA", "TGCCC", "TGCCG", "TGCCT", "TGCGA", 
            "TGCGC", "TGCGG", "TGCGT", "TGCTA", "TGCTC", "TGCTG", "TGCTT", 
            "TTCAA", "TTCAC", "TTCAG", "TTCAT", "TTCCA", "TTCCC", "TTCCG", 
            "TTCCT", "TTCGA", "TTCGC", "TTCGG", "TTCGT", "TTCTA", "TTCTC", 
            "TTCTG", "TTCTT", "AATAA", "AATAC", "AATAG", "AATAT", "AATCA", 
            "AATCC", "AATCG", "AATCT", "AATGA", "AATGC", "AATGG", "AATGT", 
            "AATTA", "AATTC", "AATTG", "AATTT", "ACTAA", "ACTAC", "ACTAG", 
            "ACTAT", "ACTCA", "ACTCC", "ACTCG", "ACTCT", "ACTGA", "ACTGC", 
            "ACTGG", "ACTGT", "ACTTA", "ACTTC", "ACTTG", "ACTTT", "AGTAA", 
            "AGTAC", "AGTAG", "AGTAT", "AGTCA", "AGTCC", "AGTCG", "AGTCT", 
            "AGTGA", "AGTGC", "AGTGG", "AGTGT", "AGTTA", "AGTTC", "AGTTG", 
            "AGTTT", "ATTAA", "ATTAC", "ATTAG", "ATTAT", "ATTCA", "ATTCC", 
            "ATTCG", "ATTCT", "ATTGA", "ATTGC", "ATTGG", "ATTGT", "ATTTA", 
            "ATTTC", "ATTTG", "ATTTT", "CATAA", "CATAC", "CATAG", "CATAT", 
            "CATCA", "CATCC", "CATCG", "CATCT", "CATGA", "CATGC", "CATGG", 
            "CATGT", "CATTA", "CATTC", "CATTG", "CATTT", "CCTAA", "CCTAC", 
            "CCTAG", "CCTAT", "CCTCA", "CCTCC", "CCTCG", "CCTCT", "CCTGA", 
            "CCTGC", "CCTGG", "CCTGT", "CCTTA", "CCTTC", "CCTTG", "CCTTT", 
            "CGTAA", "CGTAC", "CGTAG", "CGTAT", "CGTCA", "CGTCC", "CGTCG", 
            "CGTCT", "CGTGA", "CGTGC", "CGTGG", "CGTGT", "CGTTA", "CGTTC", 
            "CGTTG", "CGTTT", "CTTAA", "CTTAC", "CTTAG", "CTTAT", "CTTCA", 
            "CTTCC", "CTTCG", "CTTCT", "CTTGA", "CTTGC", "CTTGG", "CTTGT", 
            "CTTTA", "CTTTC", "CTTTG", "CTTTT", "GATAA", "GATAC", "GATAG", 
            "GATAT", "GATCA", "GATCC", "GATCG", "GATCT", "GATGA", "GATGC", 
            "GATGG", "GATGT", "GATTA", "GATTC", "GATTG", "GATTT", "GCTAA", 
            "GCTAC", "GCTAG", "GCTAT", "GCTCA", "GCTCC", "GCTCG", "GCTCT", 
            "GCTGA", "GCTGC", "GCTGG", "GCTGT", "GCTTA", "GCTTC", "GCTTG", 
            "GCTTT", "GGTAA", "GGTAC", "GGTAG", "GGTAT", "GGTCA", "GGTCC", 
            "GGTCG", "GGTCT", "GGTGA", "GGTGC", "GGTGG", "GGTGT", "GGTTA", 
            "GGTTC", "GGTTG", "GGTTT", "GTTAA", "GTTAC", "GTTAG", "GTTAT", 
            "GTTCA", "GTTCC", "GTTCG", "GTTCT", "GTTGA", "GTTGC", "GTTGG", 
            "GTTGT", "GTTTA", "GTTTC", "GTTTG", "GTTTT", "TATAA", "TATAC", 
            "TATAG", "TATAT", "TATCA", "TATCC", "TATCG", "TATCT", "TATGA", 
            "TATGC", "TATGG", "TATGT", "TATTA", "TATTC", "TATTG", "TATTT", 
            "TCTAA", "TCTAC", "TCTAG", "TCTAT", "TCTCA", "TCTCC", "TCTCG", 
            "TCTCT", "TCTGA", "TCTGC", "TCTGG", "TCTGT", "TCTTA", "TCTTC", 
            "TCTTG", "TCTTT", "TGTAA", "TGTAC", "TGTAG", "TGTAT", "TGTCA", 
            "TGTCC", "TGTCG", "TGTCT", "TGTGA", "TGTGC", "TGTGG", "TGTGT", 
            "TGTTA", "TGTTC", "TGTTG", "TGTTT", "TTTAA", "TTTAC", "TTTAG", 
            "TTTAT", "TTTCA", "TTTCC", "TTTCG", "TTTCT", "TTTGA", "TTTGC", 
            "TTTGG", "TTTGT", "TTTTA", "TTTTC", "TTTTG", "TTTTT", "AATAA", 
            "AATAC", "AATAG", "AATAT", "AATCA", "AATCC", "AATCG", "AATCT", 
            "AATGA", "AATGC", "AATGG", "AATGT", "AATTA", "AATTC", "AATTG", 
            "AATTT", "ACTAA", "ACTAC", "ACTAG", "ACTAT", "ACTCA", "ACTCC", 
            "ACTCG", "ACTCT", "ACTGA", "ACTGC", "ACTGG", "ACTGT", "ACTTA", 
            "ACTTC", "ACTTG", "ACTTT", "AGTAA", "AGTAC", "AGTAG", "AGTAT", 
            "AGTCA", "AGTCC", "AGTCG", "AGTCT", "AGTGA", "AGTGC", "AGTGG", 
            "AGTGT", "AGTTA", "AGTTC", "AGTTG", "AGTTT", "ATTAA", "ATTAC", 
            "ATTAG", "ATTAT", "ATTCA", "ATTCC", "ATTCG", "ATTCT", "ATTGA", 
            "ATTGC", "ATTGG", "ATTGT", "ATTTA", "ATTTC", "ATTTG", "ATTTT", 
            "CATAA", "CATAC", "CATAG", "CATAT", "CATCA", "CATCC", "CATCG", 
            "CATCT", "CATGA", "CATGC", "CATGG", "CATGT", "CATTA", "CATTC", 
            "CATTG", "CATTT", "CCTAA", "CCTAC", "CCTAG", "CCTAT", "CCTCA", 
            "CCTCC", "CCTCG", "CCTCT", "CCTGA", "CCTGC", "CCTGG", "CCTGT", 
            "CCTTA", "CCTTC", "CCTTG", "CCTTT", "CGTAA", "CGTAC", "CGTAG", 
            "CGTAT", "CGTCA", "CGTCC", "CGTCG", "CGTCT", "CGTGA", "CGTGC", 
            "CGTGG", "CGTGT", "CGTTA", "CGTTC", "CGTTG", "CGTTT", "CTTAA", 
            "CTTAC", "CTTAG", "CTTAT", "CTTCA", "CTTCC", "CTTCG", "CTTCT", 
            "CTTGA", "CTTGC", "CTTGG", "CTTGT", "CTTTA", "CTTTC", "CTTTG", 
            "CTTTT", "GATAA", "GATAC", "GATAG", "GATAT", "GATCA", "GATCC", 
            "GATCG", "GATCT", "GATGA", "GATGC", "GATGG", "GATGT", "GATTA", 
            "GATTC", "GATTG", "GATTT", "GCTAA", "GCTAC", "GCTAG", "GCTAT", 
            "GCTCA", "GCTCC", "GCTCG", "GCTCT", "GCTGA", "GCTGC", "GCTGG", 
            "GCTGT", "GCTTA", "GCTTC", "GCTTG", "GCTTT", "GGTAA", "GGTAC", 
            "GGTAG", "GGTAT", "GGTCA", "GGTCC", "GGTCG", "GGTCT", "GGTGA", 
            "GGTGC", "GGTGG", "GGTGT", "GGTTA", "GGTTC", "GGTTG", "GGTTT", 
            "GTTAA", "GTTAC", "GTTAG", "GTTAT", "GTTCA", "GTTCC", "GTTCG", 
            "GTTCT", "GTTGA", "GTTGC", "GTTGG", "GTTGT", "GTTTA", "GTTTC", 
            "GTTTG", "GTTTT", "TATAA", "TATAC", "TATAG", "TATAT", "TATCA", 
            "TATCC", "TATCG", "TATCT", "TATGA", "TATGC", "TATGG", "TATGT", 
            "TATTA", "TATTC", "TATTG", "TATTT", "TCTAA", "TCTAC", "TCTAG", 
            "TCTAT", "TCTCA", "TCTCC", "TCTCG", "TCTCT", "TCTGA", "TCTGC", 
            "TCTGG", "TCTGT", "TCTTA", "TCTTC", "TCTTG", "TCTTT", "TGTAA", 
            "TGTAC", "TGTAG", "TGTAT", "TGTCA", "TGTCC", "TGTCG", "TGTCT", 
            "TGTGA", "TGTGC", "TGTGG", "TGTGT", "TGTTA", "TGTTC", "TGTTG", 
            "TGTTT", "TTTAA", "TTTAC", "TTTAG", "TTTAT", "TTTCA", "TTTCC", 
            "TTTCG", "TTTCT", "TTTGA", "TTTGC", "TTTGG", "TTTGT", "TTTTA", 
            "TTTTC", "TTTTG", "TTTTT", "AATAA", "AATAC", "AATAG", "AATAT", 
            "AATCA", "AATCC", "AATCG", "AATCT", "AATGA", "AATGC", "AATGG", 
            "AATGT", "AATTA", "AATTC", "AATTG", "AATTT", "ACTAA", "ACTAC", 
            "ACTAG", "ACTAT", "ACTCA", "ACTCC", "ACTCG", "ACTCT", "ACTGA", 
            "ACTGC", "ACTGG", "ACTGT", "ACTTA", "ACTTC", "ACTTG", "ACTTT", 
            "AGTAA", "AGTAC", "AGTAG", "AGTAT", "AGTCA", "AGTCC", "AGTCG", 
            "AGTCT", "AGTGA", "AGTGC", "AGTGG", "AGTGT", "AGTTA", "AGTTC", 
            "AGTTG", "AGTTT", "ATTAA", "ATTAC", "ATTAG", "ATTAT", "ATTCA", 
            "ATTCC", "ATTCG", "ATTCT", "ATTGA", "ATTGC", "ATTGG", "ATTGT", 
            "ATTTA", "ATTTC", "ATTTG", "ATTTT", "CATAA", "CATAC", "CATAG", 
            "CATAT", "CATCA", "CATCC", "CATCG", "CATCT", "CATGA", "CATGC", 
            "CATGG", "CATGT", "CATTA", "CATTC", "CATTG", "CATTT", "CCTAA", 
            "CCTAC", "CCTAG", "CCTAT", "CCTCA", "CCTCC", "CCTCG", "CCTCT", 
            "CCTGA", "CCTGC", "CCTGG", "CCTGT", "CCTTA", "CCTTC", "CCTTG", 
            "CCTTT", "CGTAA", "CGTAC", "CGTAG", "CGTAT", "CGTCA", "CGTCC", 
            "CGTCG", "CGTCT", "CGTGA", "CGTGC", "CGTGG", "CGTGT", "CGTTA", 
            "CGTTC", "CGTTG", "CGTTT", "CTTAA", "CTTAC", "CTTAG", "CTTAT", 
            "CTTCA", "CTTCC", "CTTCG", "CTTCT", "CTTGA", "CTTGC", "CTTGG", 
            "CTTGT", "CTTTA", "CTTTC", "CTTTG", "CTTTT", "GATAA", "GATAC", 
            "GATAG", "GATAT", "GATCA", "GATCC", "GATCG", "GATCT", "GATGA", 
            "GATGC", "GATGG", "GATGT", "GATTA", "GATTC", "GATTG", "GATTT", 
            "GCTAA", "GCTAC", "GCTAG", "GCTAT", "GCTCA", "GCTCC", "GCTCG", 
            "GCTCT", "GCTGA", "GCTGC", "GCTGG", "GCTGT", "GCTTA", "GCTTC", 
            "GCTTG", "GCTTT", "GGTAA", "GGTAC", "GGTAG", "GGTAT", "GGTCA", 
            "GGTCC", "GGTCG", "GGTCT", "GGTGA", "GGTGC", "GGTGG", "GGTGT", 
            "GGTTA", "GGTTC", "GGTTG", "GGTTT", "GTTAA", "GTTAC", "GTTAG", 
            "GTTAT", "GTTCA", "GTTCC", "GTTCG", "GTTCT", "GTTGA", "GTTGC", 
            "GTTGG", "GTTGT", "GTTTA", "GTTTC", "GTTTG", "GTTTT", "TATAA", 
            "TATAC", "TATAG", "TATAT", "TATCA", "TATCC", "TATCG", "TATCT", 
            "TATGA", "TATGC", "TATGG", "TATGT", "TATTA", "TATTC", "TATTG", 
            "TATTT", "TCTAA", "TCTAC", "TCTAG", "TCTAT", "TCTCA", "TCTCC", 
            "TCTCG", "TCTCT", "TCTGA", "TCTGC", "TCTGG", "TCTGT", "TCTTA", 
            "TCTTC", "TCTTG", "TCTTT", "TGTAA", "TGTAC", "TGTAG", "TGTAT", 
            "TGTCA", "TGTCC", "TGTCG", "TGTCT", "TGTGA", "TGTGC", "TGTGG", 
            "TGTGT", "TGTTA", "TGTTC", "TGTTG", "TGTTT", "TTTAA", "TTTAC", 
            "TTTAG", "TTTAT", "TTTCA", "TTTCC", "TTTCG", "TTTCT", "TTTGA", 
            "TTTGC", "TTTGG", "TTTGT", "TTTTA", "TTTTC", "TTTTG", "TTTTT"
          )),
      class = c("data.table", "data.frame"),
      row.names = c(NA, -1536L)
      #, .internal.selfref = <pointer: 0x0000000006221ef0>
    )
  
  .ct.DNS78.row.headers <<- 
    structure(
      list(
        Ref =
          c("AC", "AC", "AC", "AC", "AC", "AC", "AC", 
            "AC", "AC", "AT", "AT", "AT", "AT", "AT", "AT", "CC", "CC", "CC", 
            "CC", "CC", "CC", "CC", "CC", "CC", "CG", "CG", "CG", "CG", "CG", 
            "CG", "CT", "CT", "CT", "CT", "CT", "CT", "CT", "CT", "CT", "GC", 
            "GC", "GC", "GC", "GC", "GC", "TA", "TA", "TA", "TA", "TA", "TA", 
            "TC", "TC", "TC", "TC", "TC", "TC", "TC", "TC", "TC", "TG", "TG", 
            "TG", "TG", "TG", "TG", "TG", "TG", "TG", "TT", "TT", "TT", "TT", 
            "TT", "TT", "TT", "TT", "TT"),
        Var = c("CA", "CG", "CT", "GA", 
                "GG", "GT", "TA", "TG", "TT", "CA", "CC", "CG", "GA", "GC", "TA", 
                "AA", "AG", "AT", "GA", "GG", "GT", "TA", "TG", "TT", "AT", "GC", 
                "GT", "TA", "TC", "TT", "AA", "AC", "AG", "GA", "GC", "GG", "TA", 
                "TC", "TG", "AA", "AG", "AT", "CA", "CG", "TA", "AT", "CG", "CT", 
                "GC", "GG", "GT", "AA", "AG", "AT", "CA", "CG", "CT", "GA", "GG", 
                "GT", "AA", "AC", "AT", "CA", "CC", "CT", "GA", "GC", "GT", "AA", 
                "AC", "AG", "CA", "CC", "CG", "GA", "GC", "GG")), 
      class = c("data.table", "data.frame"),
      row.names = c(NA, -78L)
      # ,  .internal.selfref = <pointer: 0x0000000006221ef0>
    )
  
  .ct.ID.row.headers <<-
    structure(
      list(
        Type = 
          c("DEL", "DEL", "DEL", "DEL", "DEL", "DEL", 
            "DEL", "DEL", "DEL", "DEL", "DEL", "DEL", "INS", "INS", "INS", 
            "INS", "INS", "INS", "INS", "INS", "INS", "INS", "INS", "INS", 
            "DEL", "DEL", "DEL", "DEL", "DEL", "DEL", "DEL", "DEL", "DEL", 
            "DEL", "DEL", "DEL", "DEL", "DEL", "DEL", "DEL", "DEL", "DEL", 
            "DEL", "DEL", "DEL", "DEL", "DEL", "DEL", "INS", "INS", "INS", 
            "INS", "INS", "INS", "INS", "INS", "INS", "INS", "INS", "INS", 
            "INS", "INS", "INS", "INS", "INS", "INS", "INS", "INS", "INS", 
            "INS", "INS", "INS", "DEL", "DEL", "DEL", "DEL", "DEL", "DEL", 
            "DEL", "DEL", "DEL", "DEL", "DEL"), 
        Subtype =
          c("C", "C", "C", 
            "C", "C", "C", "T", "T", "T", "T", "T", "T", "C", "C", "C", "C", 
            "C", "C", "T", "T", "T", "T", "T", "T", "repeats", "repeats", 
            "repeats", "repeats", "repeats", "repeats", "repeats", "repeats", 
            "repeats", "repeats", "repeats", "repeats", "repeats", "repeats", 
            "repeats", "repeats", "repeats", "repeats", "repeats", "repeats", 
            "repeats", "repeats", "repeats", "repeats", "repeats", "repeats", 
            "repeats", "repeats", "repeats", "repeats", "repeats", "repeats", 
            "repeats", "repeats", "repeats", "repeats", "repeats", "repeats", 
            "repeats", "repeats", "repeats", "repeats", "repeats", "repeats", 
            "repeats", "repeats", "repeats", "repeats", "MH", "MH", "MH", 
            "MH", "MH", "MH", "MH", "MH", "MH", "MH", "MH"),
        Indel_size =
          c("1", 
            "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", 
            "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "2", "2", "2", 
            "2", "2", "2", "3", "3", "3", "3", "3", "3", "4", "4", "4", "4", 
            "4", "4", "5+", "5+", "5+", "5+", "5+", "5+", "2", "2", "2", 
            "2", "2", "2", "3", "3", "3", "3", "3", "3", "4", "4", "4", "4", 
            "4", "4", "5+", "5+", "5+", "5+", "5+", "5+", "2", "3", "3", 
            "4", "4", "4", "5+", "5+", "5+", "5+", "5+"),
        Repeat_MH_size
        = c("0", 
            "1", "2", "3", "4", "5+", "0", "1", "2", "3", "4", "5+", "0", 
            "1", "2", "3", "4", "5+", "0", "1", "2", "3", "4", "5+", "0", 
            "1", "2", "3", "4", "5+", "0", "1", "2", "3", "4", "5+", "0", 
            "1", "2", "3", "4", "5+", "0", "1", "2", "3", "4", "5+", "0", 
            "1", "2", "3", "4", "5+", "0", "1", "2", "3", "4", "5+", "0", 
            "1", "2", "3", "4", "5+", "0", "1", "2", "3", "4", "5+", "1", 
            "1", "2", "1", "2", "3", "1", "2", "3", "4", "5+")), 
      class = 
        c("data.table", "data.frame"), row.names = c(NA, -83L)
      #, .internal.selfref = <pointer: 0x0000000008dc1ef0>
    )
  # Create a list of empty matrices
  empty96 <- matrix(0, nrow = 96, ncol = 0)
  rownames(empty96) <- .catalog.row.order96
  
  empty192 <- matrix(0, nrow = 192, ncol = 0)
  rownames(empty192) <- .catalog.row.order192
  
  empty1536 <- matrix(0, nrow = 1536, ncol = 0)
  rownames(empty1536) <- .catalog.row.order1536
  
  emptyDNS78 <- matrix(0, nrow = 78, ncol = 0)
  rownames(emptyDNS78) <- .catalog.row.order.DNS
  
  empty.cats <<- list(cat96 = empty96,
                      cat192 = empty192,
                      cat1536 = empty1536,
                      catDNS78 <- emptyDNS78)
}

