context("Mutational signature matching")
library(SynSig)

# There are test data generated by
#
## This is the function call that saved the data to .../data/
# usethis::use_data(.test.extracted.sigs, .test.ground.truth.sigs, .test.match.out, internal = TRUE, overwrite = TRUE)
#
# This just creates the directory structure:
# usethis::use_testthat()

test_that("MatchSigs2Directions", {
  load("test.data.for.matchsigs.Rdata")
  expect_equal(
    MatchSigs2Directions(.test.extracted.sigs, .test.ground.truth.sigs),
    .test.match.out)
})
