# ReadWriteCatalogs.R

#' Read a COMPOSITE catalog
#'
#' A COMPOSITE catalog is an rbind
#' of a 1536 catalog, a DBS catalog, and an ID catalog.
#' This function does not read SignatureAnalyzer
#' signatures as found on the PCAWG7 Synapse web
#' site, but rather
#' as generated by this package for analysis by
#' SignatureAnalyzer.
#'
#' @seealso \code{\link{WriteCatCOMPOSITE}}
#'
#' @param path Path of the file to read from.
#'
#' @param strict For compatibility with other \code{ReadCat} functions; ignored.
#'
#' @return An in memory matrix corresponding to the
#' contents of the file at \code{path}.
#'
#' @importFrom utils read.csv
#'
#' @keywords internal

ReadCatCOMPOSITE <- function(path, strict = FALSE) {
  retval <- read.csv(path, header = T, row.names = 1)
  return(as.matrix(retval))
}

#' Write a COMPOSITE catalog or signature matrix to disk
#'
#' @param ct A catalog or signature matrix
#'
#' @param path Path to file to write
#'
#' @importFrom utils write.csv
#'
#' @seealso \code{\link{ReadCatCOMPOSITE}}
#'
#' @export
# Exported because of Create.pancreas.Rmd, Create.2.7a.7b.Rmd, etc.

WriteCatCOMPOSITE <- function(ct, path) {
  write.csv(ct, file = path, row.names = TRUE,
            quote = FALSE)
}
