
#' Summarize 96-channel results from SignatureEstimation.
#'
#' @param third.level.dir Lowest level path to results, e.g.
#' \code{<top.dir>}\code{/sa.sa.96/SignatureEstimation.results/} or
#' \code{<top.dir>}\code{/sp.sp/SignatureEstimation.results/}
#' Here, \code{<top.dir>} refers to a top-level directory which contains the
#' full information of a synthetic dataset. (e.g. \code{syn.2.7a.7b.abst.v8})
#' This code depends on a conventional directory structure documented
#' elsewhere. However in \code{<third.level.dir>} there should be files
#' \code{attributed.exposures.QP.csv} and \code{attributed.exposures.SA.csv}
#' which store SignatureEstimation results.
#'
#' @param ground.truth.exposure.name File name which stores ground-truth exposures;
#' defaults to \code{"ground.truth.syn.exposures.csv"}.
#' This file can be found in the \code{sub.dir}, i.e. \code{<third.level.dir>/../}
#'
#' @param overwrite If TRUE overwrite existing directories and files.
#'
#'
#' @export
#'
#' @importFrom ICAMS WriteCatSNS96 ReadCatSNS96
#' @importFrom utils capture.output sessionInfo
#' @importFrom grDevices dev.off
#' @importFrom graphics par
#'
SummarizeSigOneSE96Subdir <-
  function(third.level.dir,
           ground.truth.exposure.name = "ground.truth.syn.exposures.csv",
           overwrite = FALSE) {

    # Location of SignatureEstimation output, which is our input
    # inputPath may change if sigproextractor updates!
    inputPath <- paste0(third.level.dir)
    stopifnot(dir.exists(inputPath))

    # SignatureEstimation cannot extract signatures,
	# Therefore from sub.dir we copy ground-truth signatures in ICAMS format.
	# In the analysis, we regard the ground-truth signatures as
	# the signatures extracted by SignatureEstimation.
    # Ground-truth signatures will be copied into the /summary folder.
    ground.truth.sigs.path <- paste0(inputPath,"/../ground.truth.syn.sigs.csv")

    # Read in attributed exposures
	# Note: There are two attributed files generated by different methods,
	# Quadratic Programming (QP) and Simulated Annealing (SA)
	attributed.exp.path <- list()
    attributed.exp.path[["QP"]] <- paste0(inputPath,"/attributed.exposures.QP.csv")
    attributed.exp.path[["SA"]] <- paste0(inputPath,"/attributed.exposures.SA.csv")

    # Return value of this function is an embedded list.
	retval <- list()

    # For attributed exposures using Quadratic Programming,
	# SummarizeSigOneSubdir will generate a "/summary.QP" folder
    # under third.level.dir. Summarized results are dumped into
    # this folder.
    retval[["QP"]] <-
      SummarizeSigOneSubdir(
        third.level.dir = third.level.dir,
        ground.truth.exposure.name = ground.truth.exposure.name,
        extracted.sigs.path = ground.truth.sigs.path,
        attributed.exp.path = attributed.exp.path[["QP"]],
        read.extracted.sigs.fn = ReadCatSNS96,
        read.ground.truth.sigs.fn = ReadCatSNS96,
        write.cat.fn = WriteCatSNS96,
        plot.pdf.fn = PlotCatSNS96ToPdf,
        overwrite = overwrite,
        summary.folder.name = "summary.QP")

    # For attributed exposures using Simulated Annealing,
	# SummarizeSigOneSubdir will generate a "/summary.QP" folder
    # under third.level.dir. Summarized results are dumped into
    # this folder.
    retval[["SA"]] <-
      SummarizeSigOneSubdir(
        third.level.dir = third.level.dir,
        ground.truth.exposure.name = ground.truth.exposure.name,
        extracted.sigs.path = ground.truth.sigs.path,
        attributed.exp.path = attributed.exp.path[["SA"]],
        read.extracted.sigs.fn = ReadCatSNS96,
        read.ground.truth.sigs.fn = ReadCatSNS96,
        write.cat.fn = WriteCatSNS96,
        plot.pdf.fn = PlotCatSNS96ToPdf,
        overwrite = overwrite,
        summary.folder.name = "summary.SA")

    invisible(retval) # So we can test without looking at a file.
}
